-- Shelfy control.sqlite at schema v6, with synthetic data in every table.
-- Generated by `SHELFY_BLESS=1 cargo test -p shelfy-core --test schema`; do not edit.
PRAGMA foreign_keys = OFF;
BEGIN;
CREATE TABLE users (
  id TEXT PRIMARY KEY,                               -- ULID
  email TEXT NOT NULL UNIQUE COLLATE NOCASE,
  display_name TEXT,
  role TEXT NOT NULL CHECK (role IN ('owner','member')),
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active','disabled','deleting')),
  quota_bytes INTEGER NOT NULL,                      -- media + DB; owner: 0 = unlimited
  capture_daily_limit INTEGER NOT NULL DEFAULT 20,
  usage_bytes INTEGER NOT NULL DEFAULT 0, usage_updated_at INTEGER,
  disclaimer_version TEXT, disclaimer_accepted_at INTEGER,
  created_at INTEGER NOT NULL, last_seen_at INTEGER
, privacy_version TEXT, privacy_accepted_at INTEGER, usage_media_bytes INTEGER NOT NULL DEFAULT 0, usage_db_bytes INTEGER NOT NULL DEFAULT 0);
CREATE TABLE invites (token_hash BLOB PRIMARY KEY, email TEXT, role TEXT NOT NULL DEFAULT 'member',
  created_by TEXT NOT NULL REFERENCES users(id), created_at INTEGER NOT NULL,
  expires_at INTEGER NOT NULL, used_at INTEGER, used_by TEXT);
CREATE TABLE sessions (id_hash BLOB PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at INTEGER NOT NULL, expires_at INTEGER NOT NULL, last_seen_at INTEGER NOT NULL,
  reauth_at INTEGER, user_agent TEXT);
CREATE TABLE magic_links (token_hash BLOB PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  purpose TEXT NOT NULL CHECK (purpose IN ('login','verify','reauth')),
  expires_at INTEGER NOT NULL, used_at INTEGER);
CREATE TABLE pairing_codes (code_hash BLOB PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  kind TEXT NOT NULL, expires_at INTEGER NOT NULL, used_at INTEGER);
CREATE TABLE provider_keys (user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  provider_id TEXT NOT NULL, key_version INTEGER NOT NULL, nonce BLOB NOT NULL, ciphertext BLOB NOT NULL,
  last4 TEXT NOT NULL, created_at INTEGER NOT NULL, last_used_at INTEGER,
  PRIMARY KEY (user_id, provider_id));
CREATE TABLE jobs (
  id INTEGER PRIMARY KEY,
  user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  kind TEXT NOT NULL, dedupe_key TEXT,
  state TEXT NOT NULL CHECK (state IN ('queued','running','succeeded','failed','cancelled')),
  priority INTEGER NOT NULL DEFAULT 100,
  payload_json TEXT NOT NULL DEFAULT '{}',
  attempts INTEGER NOT NULL DEFAULT 0, max_attempts INTEGER NOT NULL,
  run_at INTEGER NOT NULL, lease_until INTEGER,
  progress REAL, stage TEXT, error_code TEXT, error_detail TEXT,
  created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL, finished_at INTEGER
);
CREATE UNIQUE INDEX jobs_active_dedupe ON jobs(user_id, kind, dedupe_key)
  WHERE state IN ('queued','running') AND dedupe_key IS NOT NULL;
CREATE INDEX jobs_ready ON jobs(kind, state, run_at);
CREATE INDEX jobs_user ON jobs(user_id, state, kind);
CREATE TABLE queue_state (user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, kind TEXT NOT NULL,
  paused INTEGER NOT NULL DEFAULT 0, PRIMARY KEY (user_id, kind));
CREATE TABLE uploads (id TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  purpose TEXT NOT NULL, length INTEGER NOT NULL, upload_offset INTEGER NOT NULL DEFAULT 0, meta_json TEXT,
  created_at INTEGER NOT NULL, expires_at INTEGER NOT NULL, completed_at INTEGER);
CREATE TABLE idempotency (user_id TEXT NOT NULL, key TEXT NOT NULL, status INTEGER NOT NULL, body BLOB,
  created_at INTEGER NOT NULL, PRIMARY KEY (user_id, key));
CREATE TABLE usage_daily (user_id TEXT NOT NULL, day TEXT NOT NULL,
  ai_calls INTEGER NOT NULL DEFAULT 0, ai_in_tokens INTEGER NOT NULL DEFAULT 0, ai_out_tokens INTEGER NOT NULL DEFAULT 0,
  captures INTEGER NOT NULL DEFAULT 0, ingest_items INTEGER NOT NULL DEFAULT 0, bytes_in INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY (user_id, day));
CREATE TABLE audit_log (id INTEGER PRIMARY KEY, at INTEGER NOT NULL, actor_user_id TEXT, action TEXT NOT NULL,
  target TEXT, ip_hash BLOB, meta_json TEXT);
CREATE TABLE feature_flags (key TEXT PRIMARY KEY, value_json TEXT NOT NULL, updated_at INTEGER NOT NULL);
CREATE TABLE passkeys (id INTEGER PRIMARY KEY AUTOINCREMENT, user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  cred_id BLOB NOT NULL UNIQUE, passkey_json TEXT NOT NULL, label TEXT,
  created_at INTEGER NOT NULL, last_used_at INTEGER);
CREATE TABLE exports (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  job_id INTEGER NOT NULL,
  created_at INTEGER NOT NULL,
  expires_at INTEGER NOT NULL,
  estimated_bytes INTEGER NOT NULL CHECK (estimated_bytes >= 0),
  bytes INTEGER CHECK (bytes >= 0),
  deleted_at INTEGER
);
CREATE UNIQUE INDEX exports_live_user ON exports(user_id) WHERE deleted_at IS NULL;
CREATE INDEX exports_expiry ON exports(expires_at);
CREATE TABLE "api_tokens" (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  kind TEXT NOT NULL CHECK (kind IN ('extension','shortcut','migrate','library')),
  token_hash BLOB NOT NULL UNIQUE,
  label TEXT,
  scopes TEXT NOT NULL,
  created_at INTEGER NOT NULL,
  last_used_at INTEGER,
  revoked_at INTEGER,
  expires_at INTEGER,
  install_hash BLOB
);
CREATE INDEX api_tokens_install ON api_tokens(user_id, install_hash) WHERE install_hash IS NOT NULL;
INSERT INTO "users" VALUES ('01J9Z3B8K4QW6TFX0V7G2N5RCA', 'owner@example.test', 'Owner', 'owner', 'active', 0, 20, 1024, 1790899200000, '2026-10', 1790899200000, 1790899200000, 1790899200000, '1', 1790899200000, 768, 256);
INSERT INTO "invites" VALUES (X'AA01', 'member@example.test', 'member', '01J9Z3B8K4QW6TFX0V7G2N5RCA', 1790899200000, 1791504000000, NULL, NULL);
INSERT INTO "sessions" VALUES (X'DD01', '01J9Z3B8K4QW6TFX0V7G2N5RCA', 1790899200000, 1793491200000, 1790899200000, NULL, 'test');
INSERT INTO "magic_links" VALUES (X'EE01', '01J9Z3B8K4QW6TFX0V7G2N5RCA', 'login', 1790900100000, NULL);
INSERT INTO "pairing_codes" VALUES (X'AB01', '01J9Z3B8K4QW6TFX0V7G2N5RCA', 'extension', 1790899260000, NULL);
INSERT INTO "provider_keys" VALUES ('01J9Z3B8K4QW6TFX0V7G2N5RCA', 'openai', 1, X'000102', X'0A0B0C', 'abcd', 1790899200000, NULL);
INSERT INTO "jobs" VALUES (1, '01J9Z3B8K4QW6TFX0V7G2N5RCA', 'archive.drain', 'archive.drain', 'queued', 100, '{}', 0, 5, 1790899200000, NULL, NULL, NULL, NULL, NULL, 1790899200000, 1790899200000, NULL);
INSERT INTO "queue_state" VALUES ('01J9Z3B8K4QW6TFX0V7G2N5RCA', 'ai.drain', 1);
INSERT INTO "uploads" VALUES ('01J9Z3B8K4QW6TFX0V7G2N5RCC', '01J9Z3B8K4QW6TFX0V7G2N5RCA', 'bookmark', 2048, 1024, '{}', 1790899200000, 1790985600000, NULL);
INSERT INTO "idempotency" VALUES ('01J9Z3B8K4QW6TFX0V7G2N5RCA', 'req-1', 202, X'7B7D', 1790899200000);
INSERT INTO "usage_daily" VALUES ('01J9Z3B8K4QW6TFX0V7G2N5RCA', '2026-10-02', 3, 1200, 300, 1, 40, 65536);
INSERT INTO "audit_log" VALUES (1, 1790899200000, '01J9Z3B8K4QW6TFX0V7G2N5RCA', 'invite.create', 'member@example.test', X'0F', '{}');
INSERT INTO "feature_flags" VALUES ('capture', 'true', 1790899200000);
INSERT INTO "passkeys" VALUES (1, '01J9Z3B8K4QW6TFX0V7G2N5RCA', X'CC01', '{}', 'Laptop', 1790899200000, NULL);
INSERT INTO "exports" VALUES ('01J9Z3B8K4QW6TFX0V7G2N5RCE', '01J9Z3B8K4QW6TFX0V7G2N5RCA', 1, 1790899200000, 1791504000000, 4096, 2048, NULL);
INSERT INTO "api_tokens" VALUES ('01J9Z3B8K4QW6TFX0V7G2N5RCB', '01J9Z3B8K4QW6TFX0V7G2N5RCA', 'extension', X'FF01', 'Chrome', 'ingest tasks uploads lookup', 1790899200000, NULL, NULL, NULL, X'FE01');
INSERT INTO "api_tokens" VALUES ('01J9Z3B8K4QW6TFX0V7G2N5RCD', '01J9Z3B8K4QW6TFX0V7G2N5RCA', 'migrate', X'FF02', 'migration', 'migrate', 1790899200000, NULL, NULL, 1791504000000, NULL);
COMMIT;
PRAGMA application_id = 1397247043;
PRAGMA user_version = 6;
