-- Shelfy library.sqlite at schema v3, with synthetic data in every table.
-- Generated by `SHELFY_BLESS=1 cargo test -p shelfy-core --test schema`; do not edit.
PRAGMA foreign_keys = OFF;
BEGIN;
CREATE TABLE posts (
  id INTEGER PRIMARY KEY,                    -- internal rowid: joins + FTS rowid
  key TEXT NOT NULL UNIQUE,                  -- public id, see §2.8
  platform TEXT NOT NULL CHECK (platform IN ('instagram','twitter','pinterest','web','manual')),
  native_id TEXT NOT NULL,
  shortcode TEXT, post_url TEXT, profile_url TEXT, author_username TEXT, author_name TEXT,
  caption TEXT,                              -- ≤ 20 000 chars
  media_type TEXT NOT NULL,                  -- image|images|carousel|video|text|website|file
  media_count INTEGER NOT NULL DEFAULT 1,
  posted_at INTEGER,                         -- ms; NULL when unknown
  imported_at INTEGER NOT NULL,
  sort_ts INTEGER NOT NULL,                  -- COALESCE(posted_at, imported_at)
  cover_object INTEGER REFERENCES media_objects(id),
  cover_url TEXT, cover_url_expires_at INTEGER,
  thumbhash BLOB,                            -- ≤ 25 bytes
  archive_state TEXT NOT NULL DEFAULT 'pending'
    CHECK (archive_state IN ('pending','partial','done','failed','client','link_only')),
  ai_status TEXT, ai_attempts INTEGER NOT NULL DEFAULT 0, ai_next_at INTEGER, ai_error TEXT,
  ai_provider TEXT, ai_model TEXT, ai_schema_version INTEGER,
  ai_description TEXT, ai_save_reason TEXT, ai_language TEXT, ai_category TEXT, ai_content_type TEXT,
  ai_tags_json TEXT, ai_entities_json TEXT, ai_keywords_json TEXT, ai_web_json TEXT, ai_analyzed_at INTEGER,
  user_note TEXT, user_tags_json TEXT,
  web_url TEXT, web_domain TEXT, web_final_url TEXT,
  current_capture_id INTEGER REFERENCES web_captures(id) ON DELETE SET NULL,
  updated_at INTEGER NOT NULL, deleted_at INTEGER, cover_fetch_attempts INTEGER NOT NULL DEFAULT 0, cover_fetch_next_at INTEGER, cover_fetch_error TEXT,
  UNIQUE (platform, native_id)
);
CREATE INDEX posts_sort      ON posts(sort_ts DESC, id DESC) WHERE deleted_at IS NULL;
CREATE INDEX posts_platform  ON posts(platform, sort_ts DESC, id DESC) WHERE deleted_at IS NULL;
CREATE INDEX posts_shortcode ON posts(shortcode) WHERE shortcode IS NOT NULL;
CREATE INDEX posts_ai        ON posts(ai_status, ai_next_at) WHERE ai_status IS NOT NULL;
CREATE INDEX posts_domain    ON posts(web_domain) WHERE web_domain IS NOT NULL;
CREATE INDEX posts_trash     ON posts(deleted_at) WHERE deleted_at IS NOT NULL;
CREATE INDEX posts_cover_object    ON posts(cover_object) WHERE cover_object IS NOT NULL;
CREATE INDEX posts_current_capture ON posts(current_capture_id) WHERE current_capture_id IS NOT NULL;
CREATE TABLE post_media (
  post_id INTEGER NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
  position INTEGER NOT NULL,
  kind TEXT NOT NULL CHECK (kind IN ('image','video','file','page')),
  source_url TEXT, source_url_expires_at INTEGER,
  video_url TEXT, video_url_expires_at INTEGER,     -- direct MP4 kept by the parser
  width INTEGER, height INTEGER, duration_ms INTEGER, label TEXT,
  object_id INTEGER REFERENCES media_objects(id),   -- archived image / poster
  video_object_id INTEGER REFERENCES media_objects(id), -- kept ("offline") video
  fetch_attempts INTEGER NOT NULL DEFAULT 0, fetch_next_at INTEGER, fetch_error TEXT,
  PRIMARY KEY (post_id, position)
) WITHOUT ROWID;
CREATE INDEX post_media_pending ON post_media(fetch_next_at) WHERE object_id IS NULL AND kind IN ('image','video');
CREATE INDEX post_media_object       ON post_media(object_id) WHERE object_id IS NOT NULL;
CREATE INDEX post_media_video_object ON post_media(video_object_id) WHERE video_object_id IS NOT NULL;
CREATE TABLE media_objects (
  id INTEGER PRIMARY KEY, sha256 BLOB NOT NULL UNIQUE,
  ext TEXT NOT NULL, mime TEXT NOT NULL, bytes INTEGER NOT NULL,
  width INTEGER, height INTEGER, duration_ms INTEGER,
  role TEXT NOT NULL,          -- image|poster|video|file|preview|screenshot|band|section|footer|filmstrip|favicon|og
  variants INTEGER NOT NULL DEFAULT 0,   -- bitmask: 1 = g480
  origin TEXT NOT NULL,        -- server|extension|upload|capture|migration
  created_at INTEGER NOT NULL, unreferenced_since INTEGER
);
CREATE TABLE collections (id INTEGER PRIMARY KEY, name TEXT NOT NULL, color TEXT NOT NULL DEFAULT '#3d5afe',
  platform TEXT, external_id TEXT, source_name TEXT, position INTEGER, created_at INTEGER NOT NULL,
  UNIQUE (platform, external_id));
CREATE TABLE post_collections (post_id INTEGER NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
  collection_id INTEGER NOT NULL REFERENCES collections(id) ON DELETE CASCADE, added_at INTEGER NOT NULL,
  PRIMARY KEY (post_id, collection_id)) WITHOUT ROWID;
CREATE INDEX post_collections_c ON post_collections(collection_id, post_id);
CREATE TABLE post_tags (post_id INTEGER NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
  tag_norm TEXT NOT NULL, tag_form TEXT NOT NULL,
  source TEXT NOT NULL CHECK (source IN ('ai','manual')),
  tier TEXT CHECK (tier IN ('general','specific')),
  PRIMARY KEY (post_id, tag_norm, source)) WITHOUT ROWID;
CREATE INDEX post_tags_norm ON post_tags(tag_norm, post_id);
CREATE TABLE post_entities (post_id INTEGER NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
  ent_norm TEXT NOT NULL, ent_form TEXT NOT NULL, PRIMARY KEY (post_id, ent_norm)) WITHOUT ROWID;
CREATE INDEX post_entities_norm ON post_entities(ent_norm, post_id);
CREATE TABLE tag_alias (alias_norm TEXT PRIMARY KEY, canonical_norm TEXT NOT NULL, canonical_form TEXT NOT NULL,
  status TEXT NOT NULL CHECK (status IN ('proposed','accepted')), created_at INTEGER NOT NULL);
CREATE TABLE tag_cluster (id INTEGER PRIMARY KEY, label TEXT NOT NULL, label_norm TEXT,
  status TEXT NOT NULL DEFAULT 'proposed', run_id INTEGER, created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL);
CREATE TABLE tag_cluster_membership (tag_norm TEXT PRIMARY KEY,
  cluster_id INTEGER NOT NULL REFERENCES tag_cluster(id) ON DELETE CASCADE);
CREATE INDEX tag_cluster_membership_cluster ON tag_cluster_membership(cluster_id);
CREATE TABLE tag_embeddings (tag_norm TEXT NOT NULL, model TEXT NOT NULL, dim INTEGER NOT NULL, vec BLOB NOT NULL,
  PRIMARY KEY (tag_norm, model)) WITHOUT ROWID;
CREATE TABLE web_captures (id INTEGER PRIMARY KEY,
  post_id INTEGER NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
  captured_at INTEGER NOT NULL, requested_url TEXT, final_url TEXT,
  status TEXT NOT NULL, partial INTEGER NOT NULL DEFAULT 0, engine TEXT, viewport TEXT,
  title TEXT, palette_json TEXT, fonts_json TEXT, tech_json TEXT, awards_json TEXT,
  meta_json TEXT, pages_json TEXT, traits_json TEXT,   -- pages_json holds text + probes, never file paths
  hero_object INTEGER REFERENCES media_objects(id), favicon_object INTEGER REFERENCES media_objects(id),
  ai_snapshot_json TEXT,                               -- frozen AI layer of this version
  created_at INTEGER NOT NULL);
CREATE INDEX web_captures_post ON web_captures(post_id, captured_at DESC);
CREATE TABLE web_capture_assets (capture_id INTEGER NOT NULL REFERENCES web_captures(id) ON DELETE CASCADE,
  page_index INTEGER NOT NULL, role TEXT NOT NULL, seq INTEGER NOT NULL,
  object_id INTEGER NOT NULL REFERENCES media_objects(id), css_top INTEGER, css_height INTEGER,
  PRIMARY KEY (capture_id, page_index, role, seq)) WITHOUT ROWID;
CREATE INDEX web_capture_assets_object ON web_capture_assets(object_id);
CREATE VIRTUAL TABLE posts_fts USING fts5(
  tags, keywords, entities, description, note, caption, author, web_text,
  content='', contentless_delete=1,
  tokenize="unicode61 remove_diacritics 2", prefix='2 3');
CREATE TABLE settings (key TEXT PRIMARY KEY, value_json TEXT NOT NULL, updated_at INTEGER NOT NULL);
CREATE TABLE notifications (id INTEGER PRIMARY KEY, kind TEXT NOT NULL, code TEXT NOT NULL,
  params_json TEXT, target TEXT, created_at INTEGER NOT NULL, read_at INTEGER);
CREATE TABLE sync_runs (id TEXT PRIMARY KEY, platform TEXT NOT NULL, source_kind TEXT NOT NULL, source_key TEXT,
  started_at INTEGER NOT NULL, finished_at INTEGER, status TEXT NOT NULL,
  scanned INTEGER NOT NULL DEFAULT 0, inserted INTEGER NOT NULL DEFAULT 0, updated INTEGER NOT NULL DEFAULT 0,
  known INTEGER NOT NULL DEFAULT 0, error_code TEXT, client_version TEXT);
CREATE TABLE sync_sources (platform TEXT NOT NULL, source_key TEXT NOT NULL,
  collection_id INTEGER REFERENCES collections(id) ON DELETE SET NULL,
  last_run_at INTEGER, newest_native_id TEXT, PRIMARY KEY (platform, source_key));
CREATE TABLE ai_cache (kind TEXT NOT NULL, key_hash BLOB NOT NULL, value_json TEXT NOT NULL, created_at INTEGER NOT NULL,
  PRIMARY KEY (kind, key_hash)) WITHOUT ROWID;
CREATE TABLE meta (key TEXT PRIMARY KEY, value TEXT NOT NULL);
CREATE VIRTUAL TABLE posts_infix USING fts5(
  text,
  content='', contentless_delete=1,
  tokenize="trigram remove_diacritics 1");
INSERT INTO "posts" VALUES (1, 'ig_3101', 'instagram', '3101', 'C0ffeeAbCdE', NULL, NULL, 'studio.example', 'Studio Example', 'Lampada da tavolo in vetro soffiato, studio di luce', 'carousel', 2, 1787443200000, 1790899200000, 1787443200000, 1, NULL, NULL, X'1D080A0382', 'done', 'done', 0, NULL, NULL, 'openai', 'model-a', 2, 'A blown-glass table lamp on a wooden desk', 'lighting ideas', 'it', 'interior', 'product', '["lampada","Glass","cuffie"]', '["Murano"]', '["blown glass","desk lamp"]', NULL, 1790812800000, 'per il soggiorno', '["Lighting","cuffie"]', NULL, NULL, NULL, NULL, 1790899200000, NULL, 0, NULL, NULL);
INSERT INTO "posts" VALUES (2, 'x_1800000000000000001', 'twitter', '1800000000000000001', NULL, NULL, NULL, 'writer', NULL, 'Notes on typography and grid systems', 'text', 1, 1790640000000, 1790899200000, 1790640000000, NULL, NULL, NULL, NULL, 'pending', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1790899200000, NULL, 0, NULL, NULL);
INSERT INTO "posts" VALUES (3, 'pin_900000000000000001', 'pinterest', '900000000000000001', NULL, NULL, NULL, NULL, NULL, 'Marble kitchen tiles', 'image', 1, 1790121600000, 1790899200000, 1790121600000, NULL, NULL, NULL, NULL, 'pending', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1790899200000, NULL, 0, NULL, NULL);
INSERT INTO "posts" VALUES (4, 'web_00a1b2c3d4e5f6a7b8c9', 'web', '00a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9', NULL, 'https://studio.example.test/', NULL, 'studio.example.test', NULL, 'Studio Example — product design', 'website', 1, NULL, 1790467200000, 1790467200000, NULL, NULL, NULL, NULL, 'pending', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'http://studio.example.test', 'studio.example.test', 'https://studio.example.test/', 1, 1790899200000, NULL, 0, NULL, NULL);
INSERT INTO "posts" VALUES (5, 'm_01J9Z3B8K4QW6TFX0V7G2N5RCE', 'manual', '01J9Z3B8K4QW6TFX0V7G2N5RCE', NULL, NULL, NULL, NULL, NULL, NULL, 'file', 1, NULL, 1790812800000, 1790812800000, NULL, NULL, NULL, NULL, 'pending', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Brief from the client', '["work"]', NULL, NULL, NULL, NULL, 1790899200000, NULL, 0, NULL, NULL);
INSERT INTO "posts" VALUES (6, 'ig_3102', 'instagram', '3102', NULL, NULL, NULL, NULL, NULL, 'Old post in the trash', 'image', 1, 1782259200000, 1790899200000, 1782259200000, NULL, NULL, NULL, NULL, 'pending', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1790899200000, 1790899200000, 0, NULL, NULL);
INSERT INTO "post_media" VALUES (1, 0, 'image', 'https://cdn.example.test/a.jpg', NULL, NULL, NULL, 1080, 1350, NULL, NULL, 2, NULL, 0, NULL, NULL);
INSERT INTO "post_media" VALUES (1, 1, 'video', 'https://cdn.example.test/b.jpg', NULL, 'https://cdn.example.test/b.mp4', 1790985600000, NULL, NULL, 12000, NULL, 3, 4, 0, NULL, NULL);
INSERT INTO "post_media" VALUES (3, 0, 'image', 'https://i.pinimg.example.test/1200x/x.jpg', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL);
INSERT INTO "post_media" VALUES (4, 0, 'page', 'https://studio.example.test/', NULL, NULL, NULL, NULL, NULL, NULL, 'Home', 5, NULL, 0, NULL, NULL);
INSERT INTO "media_objects" VALUES (1, X'0100000000000000000000000000000000000000000000000000000000000007', 'jpg', 'image/jpeg', 1001, 1080, 1350, NULL, 'image', 1, 'server', 1790899200000, NULL);
INSERT INTO "media_objects" VALUES (2, X'020000000000000000000000000000000000000000000000000000000000000E', 'jpg', 'image/jpeg', 1002, 1080, 1350, NULL, 'image', 1, 'server', 1790899200000, NULL);
INSERT INTO "media_objects" VALUES (3, X'0300000000000000000000000000000000000000000000000000000000000015', 'webp', 'image/webp', 1003, 1080, 1350, NULL, 'poster', 1, 'server', 1790899200000, NULL);
INSERT INTO "media_objects" VALUES (4, X'040000000000000000000000000000000000000000000000000000000000001C', 'mp4', 'video/mp4', 1004, 1080, 1350, 12000, 'video', 0, 'server', 1790899200000, NULL);
INSERT INTO "media_objects" VALUES (5, X'0500000000000000000000000000000000000000000000000000000000000023', 'webp', 'image/webp', 1005, 1080, 1350, NULL, 'screenshot', 0, 'server', 1790899200000, NULL);
INSERT INTO "media_objects" VALUES (6, X'060000000000000000000000000000000000000000000000000000000000002A', 'png', 'image/png', 1006, 1080, 1350, NULL, 'favicon', 0, 'server', 1790899200000, NULL);
INSERT INTO "media_objects" VALUES (7, X'0700000000000000000000000000000000000000000000000000000000000031', 'webp', 'image/webp', 1007, 1080, 1350, NULL, 'band', 0, 'server', 1790899200000, NULL);
INSERT INTO "collections" VALUES (1, 'Lighting', '#ffaa00', 'instagram', '17900000000000001', 'lighting', NULL, 1790899200000);
INSERT INTO "collections" VALUES (2, 'Inspiration', '#3d5afe', NULL, NULL, NULL, NULL, 1790899200000);
INSERT INTO "post_collections" VALUES (1, 1, 1790899200000);
INSERT INTO "post_collections" VALUES (2, 2, 1790899200000);
INSERT INTO "post_collections" VALUES (3, 1, 1790899200000);
INSERT INTO "post_collections" VALUES (4, 2, 1790899200000);
INSERT INTO "post_collections" VALUES (5, 2, 1790899200000);
INSERT INTO "post_tags" VALUES (1, 'glass', 'Glass', 'ai', 'specific');
INSERT INTO "post_tags" VALUES (1, 'headphones', 'Headphones', 'ai', NULL);
INSERT INTO "post_tags" VALUES (1, 'headphones', 'Headphones', 'manual', NULL);
INSERT INTO "post_tags" VALUES (1, 'lampada', 'lampada', 'ai', 'general');
INSERT INTO "post_tags" VALUES (1, 'lighting', 'Lighting', 'manual', NULL);
INSERT INTO "post_tags" VALUES (5, 'work', 'work', 'manual', NULL);
INSERT INTO "post_entities" VALUES (1, 'murano', 'Murano');
INSERT INTO "tag_alias" VALUES ('cuffie', 'headphones', 'Headphones', 'accepted', 1790899200000);
INSERT INTO "tag_alias" VALUES ('lampade', 'lampada', 'lampada', 'proposed', 1790899200000);
INSERT INTO "tag_cluster" VALUES (1, 'Lighting', 'lighting', 'accepted', 1, 1790899200000, 1790899200000);
INSERT INTO "tag_cluster_membership" VALUES ('lampada', 1);
INSERT INTO "tag_cluster_membership" VALUES ('glass', 1);
INSERT INTO "tag_embeddings" VALUES ('lampada', 'e5-small', 2, X'0000803F00000000');
INSERT INTO "web_captures" VALUES (1, 4, 1790467200000, 'http://studio.example.test', 'https://studio.example.test/', 'done', 0, 'playwright', '1440x900', 'Studio Example', '[{"hex":"#111111","role":"text"}]', '[{"family":"Inter"}]', '["react"]', '[]', '{"description":"Product design studio"}', '[{"url":"https://studio.example.test/","title":"Home","digest":"Selected work"}]', '{"scroll":"smooth"}', 5, 6, NULL, 1790467200000);
INSERT INTO "web_capture_assets" VALUES (1, 0, 'band', 0, 7, 0, 900);
INSERT INTO "settings" VALUES ('language', '"it"', 1790899200000);
INSERT INTO "notifications" VALUES (1, 'info', 'sync.done', '{"inserted":3}', NULL, 1790899200000, NULL);
INSERT INTO "sync_runs" VALUES ('01J9Z3B8K4QW6TFX0V7G2N5RCD', 'instagram', 'saved', 'all', 1790899140000, 1790899200000, 'done', 10, 3, 1, 6, NULL, '0.1.0');
INSERT INTO "sync_sources" VALUES ('instagram', 'folder:17900000000000001', 1, 1790899200000, '3101');
INSERT INTO "ai_cache" VALUES ('suggest', X'0102', '[]', 1790899200000);
INSERT INTO "meta" VALUES ('created_by', 'fixture');
INSERT INTO posts_fts (rowid, tags, keywords, entities, description, note, caption, author, web_text) VALUES (1, 'Glass
Headphones
lampada
Lighting
cuffie', 'blown glass
desk lamp', 'Murano', 'A blown-glass table lamp on a wooden desk', 'per il soggiorno', 'Lampada da tavolo in vetro soffiato, studio di luce', 'studio.example
Studio Example', '');
INSERT INTO posts_fts (rowid, tags, keywords, entities, description, note, caption, author, web_text) VALUES (2, '', '', '', '', '', 'Notes on typography and grid systems', 'writer', '');
INSERT INTO posts_fts (rowid, tags, keywords, entities, description, note, caption, author, web_text) VALUES (3, '', '', '', '', '', 'Marble kitchen tiles', '', '');
INSERT INTO posts_fts (rowid, tags, keywords, entities, description, note, caption, author, web_text) VALUES (4, '', '', '', '', '', 'Studio Example — product design', 'studio.example.test', 'Studio Example
Product design studio
Home
Selected work');
INSERT INTO posts_fts (rowid, tags, keywords, entities, description, note, caption, author, web_text) VALUES (5, 'work', '', '', '', 'Brief from the client', '', '', '');
INSERT INTO posts_infix (rowid, text) VALUES (1, 'Lampada da tavolo in vetro soffiato, studio di luce
A blown-glass table lamp on a wooden desk
per il soggiorno
studio.example
Studio Example
["lampada","Glass","cuffie"]
["blown glass","desk lamp"]
["Murano"]
["Lighting","cuffie"]
Glass
Headphones
Headphones
lampada
Lighting');
INSERT INTO posts_infix (rowid, text) VALUES (2, 'Notes on typography and grid systems
writer');
INSERT INTO posts_infix (rowid, text) VALUES (3, 'Marble kitchen tiles');
INSERT INTO posts_infix (rowid, text) VALUES (4, 'Studio Example — product design
studio.example.test');
INSERT INTO posts_infix (rowid, text) VALUES (5, 'Brief from the client
["work"]
work');
COMMIT;
PRAGMA application_id = 1397247042;
PRAGMA user_version = 3;
