/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

// Types of the Shelfy Web API, from crates/server/openapi.json.
// Regenerate with `pnpm exec tsx scripts/api-client/generate.ts`.

export interface paths {
  '/api/v1/auth/logout': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Signs out: ends the session of the request's cookie, if any, and clears
     *     the cookie. Answers 204 even without a session.
     */
    post: operations['logout'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/logout-all': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Signs out everywhere: ends every session of the signed-in user, this one
     *     included, and clears the cookie.
     */
    post: operations['logoutAll'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/magic-links': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Emails a sign-in link to the address, if it belongs to an account.
     * @description The answer is 202 whether or not the account exists, and whether or not
     *     email is configured (see `GET /auth/methods`). Limits: 10 requests per
     *     minute per client and 3 per hour per address (429 `rate_limited` with
     *     `Retry-After`). A malformed address answers 422 `validation_failed`.
     */
    post: operations['requestMagicLink'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/magic-links/redeem': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Redeems a sign-in link's token from a page (the token stays out of URLs
     *     and server logs).
     * @description A usable link starts a session (replacing the one the browser held);
     *     otherwise 400 `invalid_link`. The link works once.
     */
    post: operations['redeemMagicLink'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/magic/{token}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Opens a sign-in link: the URL in the email, or printed by
     *     `shelfy-server admin login-link`.
     * @description A usable link starts a session (replacing the one the browser held) and
     *     redirects to `/`; any other link redirects to `/login?error=invalid_link`.
     *     The link works once. `HEAD` never uses it up.
     */
    get: operations['openMagicLink'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/methods': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** How a user can sign in on this instance. */
    get: operations['getAuthMethods'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/collections': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Every collection, in manual order, then creation order. */
    get: operations['listCollections'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/events': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * The realtime stream of the signed-in user.
     * @description A `text/event-stream`: the `hello` event (data: `HelloEvent`), then a
     *     comment line every 20 s. The stream ends when the server shuts down;
     *     reconnect with backoff.
     */
    get: operations['streamEvents'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Who is signed in. 401 `unauthorized` without a session: the SPA shows
     *     its sign-in page.
     */
    get: operations['getMe'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/openapi.json': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** The OpenAPI document of this API. */
    get: operations['getOpenApi'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/posts': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * One page of the library (or of the trash), newest first by default.
     * @description Browsing orders page by keyset; relevance pages within the first 1,000
     *     results. The response is conditional: send the `ETag` back in
     *     `If-None-Match` and an unchanged page answers 304.
     */
    get: operations['listPosts'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/posts/{key}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** One post with everything about it, trashed or not. */
    get: operations['getPost'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/search': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Search the library: ranked by relevance when there is text, with the total.
     *     Without text, tags or concepts the answer is empty.
     */
    get: operations['search'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/stats': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** The library counters. */
    get: operations['getStats'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Liveness and readiness of the server. */
    get: operations['getHealth'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /**
     * @description Archive progress of a post's media (plan §2.13).
     * @enum {string}
     */
    ArchiveState: 'pending' | 'partial' | 'done' | 'failed' | 'client' | 'link_only';
    /**
     * @description How a user can sign in on this instance; the sign-in page reads it before
     *     anyone is signed in.
     */
    AuthMethods: {
      /**
       * @description "Email me a link" works: an email transport is configured (E4: SMTP
       *     is optional). Without it, the operator mints links with
       *     `shelfy-server admin login-link`.
       */
      emailLink: boolean;
      /** @description Passkey sign-in (P1-13). Always false for now. */
      passkeys: boolean;
    };
    /**
     * @description Result of one check.
     * @enum {string}
     */
    CheckStatus: 'ok' | 'fail';
    /**
     * @description A collection ("source" in the UI): a manual one, or a saved folder or board
     *     linked to a platform.
     */
    Collection: {
      /** @description Hex color, `#rrggbb` or `#rgb`. */
      color: string;
      /**
       * Format: int64
       * @description Posts in the collection, trash excluded.
       */
      count: number;
      /**
       * Format: int64
       * @description Creation time.
       */
      createdAt: number;
      /** @description Folder or board id on that platform. */
      externalId: string | null;
      /**
       * Format: int64
       * @description Id, the value of the `collection` filter.
       */
      id: number;
      /** @description Name. */
      name: string;
      platform: components['schemas']['Platform'] | null;
      /**
       * Format: int64
       * @description Manual order, when set.
       */
      position: number | null;
      /** @description Name of the folder or board when it was linked. */
      sourceName: string | null;
    };
    /** @description Every collection, in manual order, then creation order. */
    CollectionList: {
      /** @description The collections. */
      items: components['schemas']['Collection'][];
    };
    /**
     * @description Stable, machine-readable error codes. Each one has a fixed HTTP status.
     *
     *     New codes may be added within `/api/v1`; existing ones never change meaning.
     * @enum {string}
     */
    ErrorCode:
      | 'bad_request'
      | 'invalid_cursor'
      | 'invalid_link'
      | 'unauthorized'
      | 'forbidden'
      | 'csrf_failed'
      | 'reauth_required'
      | 'quota_exceeded'
      | 'not_found'
      | 'method_not_allowed'
      | 'conflict'
      | 'payload_too_large'
      | 'unsupported_media_type'
      | 'validation_failed'
      | 'provider_key_invalid'
      | 'capture_blocked'
      | 'extension_outdated'
      | 'rate_limited'
      | 'internal'
      | 'unavailable'
      | 'timeout';
    /** @description One field that failed validation. */
    FieldError: {
      /** @description The field, as named in the request (camelCase). */
      field: string;
      /** @description Why the value was refused, for developers. */
      reason: string;
    };
    /** @description Health of the process. */
    Health: {
      /** @description The individual checks. */
      checks: components['schemas']['HealthChecks'];
      /** @description `ok` when every check passed. */
      status: components['schemas']['CheckStatus'];
      /** @description Version of the server build. */
      version: string;
    };
    /** @description The checks behind the overall `status`. */
    HealthChecks: {
      /** @description The control database answers a query within 2 s. */
      controlDb: components['schemas']['CheckStatus'];
    };
    /** @description The `data` of the `hello` event, the first event of every stream. */
    HelloEvent: {
      /**
       * Format: int64
       * @description Milliseconds between two heartbeat comments. A stream silent for much
       *     longer is dead: reconnect.
       */
      heartbeatMs: number;
      /** @description Version of the server build; a change means a new deploy. */
      version: string;
    };
    /** @description Body of `POST /api/v1/auth/magic-links`. */
    MagicLinkRequest: {
      /** @description The account's email address. */
      email: string;
    };
    /**
     * @description How several values of a list filter combine.
     * @enum {string}
     */
    MatchMode: 'or' | 'and';
    /** @description The signed-in user. */
    Me: {
      /**
       * Format: int64
       * @description Account creation time, unix ms.
       */
      createdAt: number;
      /** @description Sign-in email address. */
      email: string;
      /** @description User id (ULID). */
      id: string;
      /** @description Role. */
      role: components['schemas']['UserRole'];
    };
    /** @description A stored object (plan §2.13). Its URLs are same-origin and immutable. */
    MediaObject: {
      /**
       * Format: int64
       * @description Size in bytes.
       */
      bytes: number;
      /**
       * Format: int64
       * @description Duration of a video, when known.
       */
      durationMs: number | null;
      /**
       * @description The 480 px WebP rendition, `/media/<sha256>.g480.webp`; `null` when it
       *     does not exist.
       */
      g480Url: string | null;
      /**
       * Format: int64
       * @description Pixel height, when known.
       */
      height: number | null;
      /** @description MIME type. */
      mime: string;
      /** @description Lowercase hex SHA-256 of the bytes. */
      sha256: string;
      /** @description The stored bytes: `/media/<sha256>.<ext>`. */
      url: string;
      /**
       * Format: int64
       * @description Pixel width, when known.
       */
      width: number | null;
    };
    /**
     * @description Kind of post (`posts.media_type`).
     * @enum {string}
     */
    MediaType: 'image' | 'images' | 'carousel' | 'video' | 'text' | 'website' | 'file';
    /**
     * @description Source platform of a post.
     * @enum {string}
     */
    Platform: 'instagram' | 'twitter' | 'pinterest' | 'web' | 'manual';
    /** @description Posts per platform, every platform present. */
    PlatformCounts: {
      /**
       * Format: int64
       * @description Instagram.
       */
      instagram: number;
      /**
       * Format: int64
       * @description Manual bookmarks.
       */
      manual: number;
      /**
       * Format: int64
       * @description Pinterest.
       */
      pinterest: number;
      /**
       * Format: int64
       * @description X.
       */
      twitter: number;
      /**
       * Format: int64
       * @description Websites.
       */
      web: number;
    };
    /** @description A post as the gallery shows it; `PostDetail` adds the heavy fields. */
    Post: {
      /**
       * Format: int64
       * @description When the AI analysis finished.
       */
      aiAnalyzedAt: number | null;
      /** @description AI category. */
      aiCategory: string | null;
      /** @description AI content type. */
      aiContentType: string | null;
      /** @description AI description. */
      aiDescription: string | null;
      /** @description AI-detected language. */
      aiLanguage: string | null;
      /** @description AI guess of why the post was saved. */
      aiSaveReason: string | null;
      /** @description AI lifecycle status; `null` when never analyzed. */
      aiStatus: string | null;
      /** @description AI tags, as produced (display forms). */
      aiTags: string[];
      /** @description Archive progress. */
      archiveState: components['schemas']['ArchiveState'];
      /** @description Author display name (for websites: the title). */
      authorName: string | null;
      /** @description Author handle (for websites: the domain). */
      authorUsername: string | null;
      /** @description Caption. */
      caption: string | null;
      /** @description Collections the post belongs to. */
      collectionIds: number[];
      cover: components['schemas']['MediaObject'] | null;
      /** @description Remote cover URL; it may have expired. */
      coverUrl: string | null;
      /**
       * Format: int64
       * @description When the post went to the trash; `null` outside the trash.
       */
      deletedAt: number | null;
      /**
       * Format: int64
       * @description When the post entered the library.
       */
      importedAt: number;
      /** @description Public id (plan §2.8), for example `ig_3141592653589793238`. */
      key: string;
      /** @description Slides, in order. */
      media: components['schemas']['PostMedia'][];
      /**
       * Format: int64
       * @description Number of slides.
       */
      mediaCount: number;
      /** @description Kind of post. */
      mediaType: components['schemas']['MediaType'];
      /** @description Source platform. */
      platform: components['schemas']['Platform'];
      /** @description Link to the original post (for websites: the final URL). */
      postUrl: string | null;
      /**
       * Format: int64
       * @description Publication time, when known.
       */
      postedAt: number | null;
      /** @description Link to the author's profile. */
      profileUrl: string | null;
      /** @description Instagram shortcode. */
      shortcode: string | null;
      /**
       * Format: int64
       * @description Sort key of the newest/oldest orders: `postedAt`, else `importedAt`.
       */
      sortTs: number;
      /** @description ThumbHash placeholder of the cover (≤ 25 bytes), standard base64. */
      thumbhash: string | null;
      /**
       * Format: int64
       * @description Last change of the post.
       */
      updatedAt: number;
      /** @description The user's note. */
      userNote: string | null;
      /** @description The user's tags (display forms). */
      userTags: string[];
      webCapture: components['schemas']['WebCapture'] | null;
      /** @description Website domain. */
      webDomain: string | null;
      /** @description Website URL after redirects. */
      webFinalUrl: string | null;
      /** @description Website URL as saved. */
      webUrl: string | null;
    };
    /**
     * @description Everything about one post: the gallery fields plus the AI bookkeeping and
     *     the tag and entity rows.
     */
    PostDetail: components['schemas']['Post'] & {
      /**
       * Format: int64
       * @description AI attempts so far.
       */
      aiAttempts: number;
      /** @description AI entities, as produced. */
      aiEntities: string[];
      /** @description Code of the last AI error. */
      aiError: string | null;
      /** @description AI keywords. */
      aiKeywords: string[];
      /** @description Model of the AI analysis. */
      aiModel: string | null;
      /**
       * Format: int64
       * @description Next AI attempt, when backed off.
       */
      aiNextAt: number | null;
      /** @description Provider of the AI analysis. */
      aiProvider: string | null;
      /**
       * Format: int64
       * @description Version of the AI output schema.
       */
      aiSchemaVersion: number | null;
      /** @description AI design catalog of a website, as produced. */
      aiWeb: unknown;
      /**
       * Format: int64
       * @description When `coverUrl` expires, if known.
       */
      coverUrlExpiresAt: number | null;
      /** @description Entity rows. */
      entities: components['schemas']['PostEntity'][];
      /** @description Platform-native id. */
      nativeId: string;
      /** @description Tag rows, AI and manual. */
      tags: components['schemas']['PostTag'][];
    };
    /** @description An AI entity of a post. */
    PostEntity: {
      /** @description Display form. */
      entity: string;
      /** @description Normalized form, the matching key of the `entity` filter. */
      norm: string;
    };
    /** @description One slide of a post. */
    PostMedia: {
      /**
       * Format: int64
       * @description Video duration, when known.
       */
      durationMs: number | null;
      /**
       * Format: int64
       * @description Pixel height, when known.
       */
      height: number | null;
      /** @description What the slide is. */
      kind: components['schemas']['SlideKind'];
      /** @description Caption of the slide (file name, page title). */
      label: string | null;
      object: components['schemas']['MediaObject'] | null;
      /**
       * Format: int64
       * @description 0-based order.
       */
      position: number;
      /** @description Remote URL of the slide; it may have expired. */
      sourceUrl: string | null;
      videoObject: components['schemas']['MediaObject'] | null;
      /**
       * Format: int64
       * @description Pixel width, when known.
       */
      width: number | null;
    };
    /** @description One page of `GET /api/v1/posts`. */
    PostPage: {
      /** @description The posts of this page. */
      items: components['schemas']['Post'][];
      /** @description Pass it as `cursor` to get the next page; `null` on the last page. */
      nextCursor: string | null;
      /**
       * Format: int64
       * @description Posts matching the filters, over all pages. Sent only with
       *     `includeTotal=true`.
       */
      total?: number;
    };
    /**
     * @description Order of a list of posts.
     * @enum {string}
     */
    PostSort: 'newest' | 'oldest' | 'relevance';
    /**
     * @description Websites or social posts.
     * @enum {string}
     */
    PostSource: 'web' | 'social';
    /**
     * @description A tag of a post, after alias resolution. An AI tag and a manual tag with
     *     the same name are two entries.
     */
    PostTag: {
      /** @description Normalized form, the matching key of the `tag` and `tags` filters. */
      norm: string;
      /** @description AI or manual. */
      source: components['schemas']['TagSource'];
      /** @description Display form. */
      tag: string;
      /** @description `general` or `specific`, for AI tags with a tier. */
      tier: string | null;
    };
    /** @description An error body: RFC 9457 problem details plus the stable `code`. */
    Problem: {
      /** @description What went wrong. Clients map it to their own message. */
      code: components['schemas']['ErrorCode'];
      /** @description Developer-facing detail. Never UI prose, user content or secrets. */
      detail?: string;
      /** @description The fields that failed validation (`validation_failed`). */
      errors?: components['schemas']['FieldError'][];
      /**
       * Format: int32
       * @description The HTTP status of the response.
       */
      status: number;
      /** @description The reason phrase of `status`. Not meant for display. */
      title: string;
      /** @description Always `about:blank`: `code` carries the problem type. */
      type: string;
    };
    /** @description Body of `POST /api/v1/auth/magic-links/redeem`. */
    RedeemRequest: {
      /** @description The link's token: the last path segment of its URL. */
      token: string;
    };
    /** @description One page of `GET /api/v1/search`. */
    SearchPage: {
      /** @description The results of this page, best match first. */
      items: components['schemas']['Post'][];
      /** @description Pass it as `cursor` to get the next page; `null` on the last page. */
      nextCursor: string | null;
      /**
       * Format: int64
       * @description Posts matching the search, over all pages (not capped by the 1,000
       *     results that relevance paging reaches).
       */
      total: number;
    };
    /**
     * @description Which posts a search covers.
     * @enum {string}
     */
    SearchScope: 'all' | 'sites' | 'social';
    /**
     * @description Kind of slide (`post_media.kind`).
     * @enum {string}
     */
    SlideKind: 'image' | 'video' | 'file' | 'page';
    /** @description Library counters. Trashed posts count only in `trashed`. */
    Stats: {
      /** @description Posts per media type; types without posts are absent. */
      byMediaType: {
        [key: string]: number;
      };
      /** @description Posts per platform. */
      byPlatform: components['schemas']['PlatformCounts'];
      /**
       * Format: int64
       * @description Posts with at least one stored object (the `stored=yes` filter).
       */
      stored: number;
      /** @description Posts per kind of stored object. */
      storedByKind: components['schemas']['StoredByKind'];
      /**
       * Format: int64
       * @description Posts in the library.
       */
      total: number;
      /**
       * Format: int64
       * @description Posts in the trash.
       */
      trashed: number;
    };
    /** @description Posts with a stored object of each kind. */
    StoredByKind: {
      /**
       * Format: int64
       * @description A stored cover.
       */
      covers: number;
      /**
       * Format: int64
       * @description At least one stored image slide.
       */
      images: number;
      /**
       * Format: int64
       * @description At least one kept video.
       */
      videos: number;
    };
    /**
     * @description Origin of a tag.
     * @enum {string}
     */
    TagSource: 'ai' | 'manual';
    /**
     * @description What a user may do on the instance.
     * @enum {string}
     */
    UserRole: 'owner' | 'member';
    /** @description The current capture of a website, without its page texts. */
    WebCapture: {
      /** @description Awards, as captured. */
      awards: unknown;
      /**
       * Format: int64
       * @description When it was captured.
       */
      capturedAt: number;
      favicon: components['schemas']['MediaObject'] | null;
      /** @description URL after redirects. */
      finalUrl: string | null;
      /** @description Fonts, as captured. */
      fonts: unknown;
      hero: components['schemas']['MediaObject'] | null;
      /**
       * Format: int64
       * @description Capture id.
       */
      id: number;
      /** @description Page metadata, as captured. */
      meta: unknown;
      /** @description Color palette, as captured. */
      palette: unknown;
      /** @description Whether some pages failed. */
      partial: boolean;
      /** @description URL the capture started from. */
      requestedUrl: string | null;
      /** @description Capture status. */
      status: string;
      /** @description Detected technologies, as captured. */
      tech: unknown;
      /** @description Page title. */
      title: string | null;
    };
    /**
     * @description A yes/no filter value.
     * @enum {string}
     */
    YesNo: 'yes' | 'no';
  };
  responses: {
    /** @description An error, as RFC 9457 problem details with a stable `code`. */
    Problem: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/problem+json': components['schemas']['Problem'];
      };
    };
  };
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  logout: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Signed out; the session cookie is cleared. */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      default: components['responses']['Problem'];
    };
  };
  logoutAll: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Every session of the user ended; the session cookie is cleared. */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      default: components['responses']['Problem'];
    };
  };
  requestMagicLink: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['MagicLinkRequest'];
      };
    };
    responses: {
      /** @description Accepted. If the address has an account, a link valid for 15 minutes is on its way. */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      default: components['responses']['Problem'];
    };
  };
  redeemMagicLink: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RedeemRequest'];
      };
    };
    responses: {
      /** @description Signed in: the response sets the session cookie. */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      default: components['responses']['Problem'];
    };
  };
  openMagicLink: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description The link's token. */
        token: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description To `/`, signed in (the response sets the session cookie), or to `/login?error=invalid_link`. */
      303: {
        headers: {
          /** @description `/` or `/login?error=invalid_link`. */
          Location?: string;
          [name: string]: unknown;
        };
        content?: never;
      };
      default: components['responses']['Problem'];
    };
  };
  getAuthMethods: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The sign-in methods this instance offers. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AuthMethods'];
        };
      };
      default: components['responses']['Problem'];
    };
  };
  listCollections: {
    parameters: {
      query?: never;
      header?: {
        /**
         * @description The `ETag` of an earlier response. When the view has not changed since,
         *     the answer is 304 with no body.
         */
        'If-None-Match'?: string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The collections. */
      200: {
        headers: {
          /** @description `private, no-cache`. */
          'Cache-Control'?: string;
          /** @description Weak ETag of this library state. */
          ETag?: string;
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CollectionList'];
        };
      };
      /** @description Unchanged since the ETag in `If-None-Match`; no body. */
      304: {
        headers: {
          /** @description The same ETag. */
          ETag?: string;
          [name: string]: unknown;
        };
        content?: never;
      };
      default: components['responses']['Problem'];
    };
  };
  streamEvents: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Server-sent events: `hello` first, then a heartbeat comment every 20 s. */
      200: {
        headers: {
          /** @description `no-store`. */
          'Cache-Control'?: string;
          /** @description `no`: proxies must not buffer the stream. */
          'X-Accel-Buffering'?: string;
          [name: string]: unknown;
        };
        content: {
          'text/event-stream': string;
        };
      };
      default: components['responses']['Problem'];
    };
  };
  getMe: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The signed-in user. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Me'];
        };
      };
      default: components['responses']['Problem'];
    };
  };
  getOpenApi: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The OpenAPI 3.1 description of this API. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': Record<string, never>;
        };
      };
      default: components['responses']['Problem'];
    };
  };
  listPosts: {
    parameters: {
      query?: {
        /** @description Only posts of this platform. */
        platform?: components['schemas']['Platform'];
        /** @description Only websites (`web`) or only everything else (`social`). */
        source?: components['schemas']['PostSource'];
        /** @description Only posts in this collection (its `id`). */
        collection?: number;
        /** @description Only posts of these kinds. Repeatable: any of them. */
        mediaType?: components['schemas']['MediaType'][];
        /** @description Only posts with (`yes`) or without (`no`) a stored object. */
        stored?: components['schemas']['YesNo'];
        /**
         * @description Only posts with (`yes`) or without (`no`) AI tags; manual tags do not
         *     count.
         */
        aiTagged?: components['schemas']['YesNo'];
        /** @description Only posts with this AI status. */
        aiStatus?: string;
        /** @description Only posts with this tag (the gallery's tag chip; always a filter). */
        tag?: string;
        /**
         * @description Tags of the AI views, combined by `tagMode`. Repeatable. With `q` in
         *     `or` mode they widen the search: a post with one of the tags or a text
         *     match is listed, and its tags add to its score.
         */
        tags?: string[];
        /** @description How `tags` combine. Default `or`. */
        tagMode?: components['schemas']['MatchMode'];
        /** @description Only posts with this AI entity. */
        entity?: string;
        /** @description Only posts with this AI category. */
        category?: string;
        /** @description Only posts with this AI content type. */
        contentType?: string;
        /**
         * @description Free-text search over tags, keywords, entities, description, note,
         *     caption, author and page text (plan §2.14). At most 500 characters.
         */
        q?: string;
        /**
         * @description Suggested concepts: more search terms, combined with `q` by
         *     `conceptMode`. Repeatable.
         */
        concept?: string[];
        /** @description How `q` and the concepts combine. Default `or`. */
        conceptMode?: components['schemas']['MatchMode'];
        /**
         * @description Order. Default `relevance` with search text (`q` or `concept`),
         *     `newest` without.
         */
        sort?: components['schemas']['PostSort'];
        /** @description List the trash instead of the library (`true` or `1`). */
        trash?: boolean;
        /** @description Page size, 1–200 (larger values are clamped). Default 60. */
        limit?: number;
        /** @description `nextCursor` of the previous page, with the same filters and sort. */
        cursor?: string;
        /** @description Add `total`, the number of matching posts, to the response. */
        includeTotal?: boolean;
      };
      header?: {
        /**
         * @description The `ETag` of an earlier response. When the view has not changed since,
         *     the answer is 304 with no body.
         */
        'If-None-Match'?: string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description One page of posts. */
      200: {
        headers: {
          /** @description `private, no-cache`. */
          'Cache-Control'?: string;
          /** @description Weak ETag of this page of this library state. */
          ETag?: string;
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PostPage'];
        };
      };
      /** @description The page is unchanged since the ETag in `If-None-Match`; no body. */
      304: {
        headers: {
          /** @description The same ETag. */
          ETag?: string;
          [name: string]: unknown;
        };
        content?: never;
      };
      default: components['responses']['Problem'];
    };
  };
  getPost: {
    parameters: {
      query?: never;
      header?: {
        /**
         * @description The `ETag` of an earlier response. When the view has not changed since,
         *     the answer is 304 with no body.
         */
        'If-None-Match'?: string;
      };
      path: {
        /** @description The post's key, for example `ig_3141592653589793238`. */
        key: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The post. */
      200: {
        headers: {
          /** @description `private, no-cache`. */
          'Cache-Control'?: string;
          /** @description Weak ETag of this post in this library state. */
          ETag?: string;
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PostDetail'];
        };
      };
      /** @description The post is unchanged since the ETag in `If-None-Match`; no body. */
      304: {
        headers: {
          /** @description The same ETag. */
          ETag?: string;
          [name: string]: unknown;
        };
        content?: never;
      };
      default: components['responses']['Problem'];
    };
  };
  search: {
    parameters: {
      query?: {
        /**
         * @description Free text, matched against tags, keywords, entities, description, note,
         *     caption, author and page text (plan §2.14). At most 500 characters.
         */
        q?: string;
        /**
         * @description Tags, combined by `tagMode`. Repeatable. With `q` in `or` mode, a post
         *     with one of the tags or a text match is a result, and its tags add to
         *     its score; in `and` mode every tag is required.
         */
        tags?: string[];
        /** @description How `tags` combine. Default `or`. */
        tagMode?: components['schemas']['MatchMode'];
        /**
         * @description Suggested concepts: more search terms, combined with `q` by
         *     `conceptMode`. Repeatable.
         */
        concept?: string[];
        /** @description How `q` and the concepts combine. Default `or`. */
        conceptMode?: components['schemas']['MatchMode'];
        /** @description `all` (default), `sites` or `social`. */
        scope?: components['schemas']['SearchScope'];
        /** @description Page size, 1–200 (larger values are clamped). Default 60. */
        limit?: number;
        /** @description `nextCursor` of the previous page, with the same criteria. */
        cursor?: string;
      };
      header?: {
        /**
         * @description The `ETag` of an earlier response. When the view has not changed since,
         *     the answer is 304 with no body.
         */
        'If-None-Match'?: string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description One page of results, best match first. */
      200: {
        headers: {
          /** @description `private, no-cache`. */
          'Cache-Control'?: string;
          /** @description Weak ETag of this page of this library state. */
          ETag?: string;
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SearchPage'];
        };
      };
      /** @description The page is unchanged since the ETag in `If-None-Match`; no body. */
      304: {
        headers: {
          /** @description The same ETag. */
          ETag?: string;
          [name: string]: unknown;
        };
        content?: never;
      };
      default: components['responses']['Problem'];
    };
  };
  getStats: {
    parameters: {
      query?: never;
      header?: {
        /**
         * @description The `ETag` of an earlier response. When the view has not changed since,
         *     the answer is 304 with no body.
         */
        'If-None-Match'?: string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The counters. */
      200: {
        headers: {
          /** @description `private, no-cache`. */
          'Cache-Control'?: string;
          /** @description Weak ETag of this library state. */
          ETag?: string;
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Stats'];
        };
      };
      /** @description Unchanged since the ETag in `If-None-Match`; no body. */
      304: {
        headers: {
          /** @description The same ETag. */
          ETag?: string;
          [name: string]: unknown;
        };
        content?: never;
      };
      default: components['responses']['Problem'];
    };
  };
  getHealth: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The server is up and its database answers. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Health'];
        };
      };
      /** @description A check failed. */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Health'];
        };
      };
      default: components['responses']['Problem'];
    };
  };
}
