// Mock dataset used across all E2E tests.
// 9 Instagram posts + 6 Twitter posts = 15 total.

export const MOCK_POSTS = [
  // ── Instagram ──────────────────────────────────────────────────────────────
  {
    id: 'ig_001', platform: 'instagram', shortcode: 'ABC001',
    postUrl: 'https://www.instagram.com/p/ABC001/',
    profileUrl: 'https://www.instagram.com/nature_pics/',
    authorUsername: 'nature_pics', authorName: 'Nature Pics',
    text: 'A beautiful mountain view #nature #travel',
    thumbnailUrl: 'https://picsum.photos/400/400?random=1',
    mediaType: 'image', timestamp: '2024-01-15T10:30:00.000Z',
    thumbnailPath: null, imagePath: null, videoPath: null,
  },
  {
    id: 'ig_002', platform: 'instagram', shortcode: 'ABC002',
    postUrl: 'https://www.instagram.com/p/ABC002/',
    profileUrl: 'https://www.instagram.com/food_lover/',
    authorUsername: 'food_lover', authorName: 'Food Lover',
    text: 'Delicious pasta recipe #foodie #cooking',
    thumbnailUrl: 'https://picsum.photos/400/400?random=2',
    mediaType: 'video', timestamp: '2024-01-14T12:00:00.000Z',
    thumbnailPath: '/local/thumb1.jpg', imagePath: null, videoPath: null,
  },
  {
    id: 'ig_003', platform: 'instagram', shortcode: 'ABC003',
    postUrl: 'https://www.instagram.com/p/ABC003/',
    profileUrl: 'https://www.instagram.com/art_studio/',
    authorUsername: 'art_studio', authorName: 'Art Studio',
    text: 'New artwork collection #art #design',
    thumbnailUrl: 'https://picsum.photos/400/400?random=3',
    mediaType: 'carousel', timestamp: '2024-01-13T09:00:00.000Z',
    thumbnailPath: null, imagePath: null, videoPath: null,
  },
  {
    id: 'ig_004', platform: 'instagram', shortcode: 'ABC004',
    postUrl: 'https://www.instagram.com/p/ABC004/',
    profileUrl: 'https://www.instagram.com/travel_blog/',
    authorUsername: 'travel_blog', authorName: 'Travel Blog',
    text: 'Sunset at the beach #travel #sunset',
    thumbnailUrl: 'https://picsum.photos/400/400?random=4',
    mediaType: 'image', timestamp: '2024-01-12T18:00:00.000Z',
    thumbnailPath: null, imagePath: null, videoPath: null,
  },
  {
    id: 'ig_005', platform: 'instagram', shortcode: 'ABC005',
    postUrl: 'https://www.instagram.com/p/ABC005/',
    profileUrl: 'https://www.instagram.com/fitness_hub/',
    authorUsername: 'fitness_hub', authorName: 'Fitness Hub',
    text: 'Morning workout routine #fitness #health',
    thumbnailUrl: 'https://picsum.photos/400/400?random=5',
    mediaType: 'video', timestamp: '2024-01-11T07:00:00.000Z',
    thumbnailPath: null, imagePath: null, videoPath: null,
  },
  {
    id: 'ig_006', platform: 'instagram', shortcode: 'ABC006',
    postUrl: 'https://www.instagram.com/p/ABC006/',
    profileUrl: 'https://www.instagram.com/tech_daily/',
    authorUsername: 'tech_daily', authorName: 'Tech Daily',
    text: 'Latest smartphone review #tech #gadgets',
    thumbnailUrl: 'https://picsum.photos/400/400?random=6',
    mediaType: 'image', timestamp: '2024-01-10T14:00:00.000Z',
    thumbnailPath: null, imagePath: null, videoPath: null,
  },
  {
    id: 'ig_007', platform: 'instagram', shortcode: 'ABC007',
    postUrl: 'https://www.instagram.com/p/ABC007/',
    profileUrl: 'https://www.instagram.com/coffee_culture/',
    authorUsername: 'coffee_culture', authorName: 'Coffee Culture',
    text: 'Perfect morning espresso #coffee #barista',
    thumbnailUrl: 'https://picsum.photos/400/400?random=7',
    mediaType: 'image', timestamp: '2024-01-09T08:00:00.000Z',
    thumbnailPath: null, imagePath: null, videoPath: null,
  },
  {
    id: 'ig_008', platform: 'instagram', shortcode: 'ABC008',
    postUrl: 'https://www.instagram.com/p/ABC008/',
    profileUrl: 'https://www.instagram.com/book_reviews/',
    authorUsername: 'book_reviews', authorName: 'Book Reviews',
    text: 'Top 10 books this month #books #reading',
    thumbnailUrl: 'https://picsum.photos/400/400?random=8',
    mediaType: 'carousel', timestamp: '2024-01-08T16:00:00.000Z',
    thumbnailPath: null, imagePath: null, videoPath: null,
  },
  {
    id: 'ig_009', platform: 'instagram', shortcode: 'ABC009',
    postUrl: 'https://www.instagram.com/p/ABC009/',
    profileUrl: 'https://www.instagram.com/plants_care/',
    authorUsername: 'plants_care', authorName: 'Plants Care',
    text: 'How to care for succulents #plants #garden',
    thumbnailUrl: 'https://picsum.photos/400/400?random=9',
    mediaType: 'text', timestamp: '2024-01-07T11:00:00.000Z',
    thumbnailPath: null, imagePath: null, videoPath: null,
  },
  // ── Twitter ────────────────────────────────────────────────────────────────
  {
    id: 'tw_001', platform: 'twitter', shortcode: null,
    postUrl: 'https://x.com/devdude/status/001',
    profileUrl: 'https://x.com/devdude',
    authorUsername: 'devdude', authorName: 'Dev Dude',
    text: 'Just shipped a new feature! async pipeline now handles 10x throughput #coding #tech',
    thumbnailUrl: 'https://picsum.photos/400/400?random=10',
    mediaType: 'image', timestamp: '2024-01-15T22:00:00.000Z',
    thumbnailPath: null, imagePath: null, videoPath: null,
  },
  {
    id: 'tw_002', platform: 'twitter', shortcode: null,
    postUrl: 'https://x.com/sciencenews/status/002',
    profileUrl: 'https://x.com/sciencenews',
    authorUsername: 'sciencenews', authorName: 'Science News',
    text: 'Breakthrough in quantum computing announced today #science #quantum',
    thumbnailUrl: 'https://picsum.photos/400/400?random=11',
    mediaType: 'image', timestamp: '2024-01-14T15:00:00.000Z',
    thumbnailPath: null, imagePath: null, videoPath: null,
  },
  {
    id: 'tw_003', platform: 'twitter', shortcode: null,
    postUrl: 'https://x.com/musicfan/status/003',
    profileUrl: 'https://x.com/musicfan',
    authorUsername: 'musicfan', authorName: 'Music Fan',
    text: 'This new album is absolutely incredible #music #newrelease',
    thumbnailUrl: 'https://picsum.photos/400/400?random=12',
    mediaType: 'video', timestamp: '2024-01-13T20:00:00.000Z',
    thumbnailPath: null, imagePath: null, videoPath: null,
  },
  {
    id: 'tw_004', platform: 'twitter', shortcode: null,
    postUrl: 'https://x.com/designpro/status/004',
    profileUrl: 'https://x.com/designpro',
    authorUsername: 'designpro', authorName: 'Design Pro',
    text: 'Color theory basics every designer should know #design #ux',
    thumbnailUrl: 'https://picsum.photos/400/400?random=13',
    mediaType: 'image', timestamp: '2024-01-12T13:00:00.000Z',
    thumbnailPath: null, imagePath: null, videoPath: null,
  },
  {
    id: 'tw_005', platform: 'twitter', shortcode: null,
    postUrl: 'https://x.com/cryptonews/status/005',
    profileUrl: 'https://x.com/cryptonews',
    authorUsername: 'cryptonews', authorName: 'Crypto News',
    text: 'Market analysis for the week ahead #crypto #finance',
    thumbnailUrl: 'https://picsum.photos/400/400?random=14',
    mediaType: 'image', timestamp: '2024-01-11T10:00:00.000Z',
    thumbnailPath: null, imagePath: null, videoPath: null,
  },
  {
    id: 'tw_006', platform: 'twitter', shortcode: null,
    postUrl: 'https://x.com/photoart/status/006',
    profileUrl: 'https://x.com/photoart',
    authorUsername: 'photoart', authorName: 'Photo Art',
    text: 'Street photography collection from Tokyo #photography #japan',
    thumbnailUrl: 'https://picsum.photos/400/400?random=15',
    mediaType: 'carousel', timestamp: '2024-01-10T09:00:00.000Z',
    thumbnailPath: null, imagePath: null, videoPath: null,
  },
];

export const MOCK_STATS = {
  total: 15,
  byPlatform: { instagram: 9, twitter: 6 },
  byMediaType: { image: 7, video: 3, carousel: 2, text: 1 },
  downloaded: 1,
  downloadedByType: { thumbnails: 1, images: 0, videos: 0 },
};

export const MOCK_DOWNLOAD_JOBS = [
  { postId: 'ig_001', platform: 'instagram', assetType: 'thumbnail', status: 'done',        progress: 1,    error: null },
  { postId: 'ig_002', platform: 'instagram', assetType: 'image',     status: 'downloading', progress: 0.65, error: null },
  { postId: 'tw_001', platform: 'twitter',   assetType: 'video',     status: 'error',       progress: 0,    error: 'Network timeout' },
  { postId: 'tw_002', platform: 'twitter',   assetType: 'thumbnail', status: 'pending',     progress: 0,    error: null },
];
