// Writes (or checks) web/src/api/schema.d.ts: the TypeScript types of the
// Shelfy Web HTTP API, generated by openapi-typescript from the committed
// OpenAPI document crates/server/openapi.json (plan D6, §2.19).
//
//   pnpm exec tsx scripts/api-client/generate.ts           # rewrite the file
//   pnpm exec tsx scripts/api-client/generate.ts --check   # fail if it is stale
//
// The chain has two checked links, both run by CI:
//   Rust types → crates/server/openapi.json   `cargo test -p shelfy-server --test openapi`
//                                             (UPDATE_OPENAPI=1 rewrites it)
//   openapi.json → web/src/api/schema.d.ts    this script with --check
// After changing a route, regenerate both and commit them.
//
// The output is formatted with the repository's prettier settings, as the
// pre-commit hook would, so a fresh run and the committed file compare byte
// for byte.

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import openapiTS, { astToString, COMMENT_HEADER, type OpenAPI3 } from 'openapi-typescript';
import * as prettier from 'prettier';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
const SOURCE = path.join(ROOT, 'crates/server/openapi.json');
const OUTPUT = path.join(ROOT, 'web/src/api/schema.d.ts');
const COMMAND = 'pnpm exec tsx scripts/api-client/generate.ts';

/** The generated file, formatted. */
async function render(): Promise<string> {
  const document = JSON.parse(fs.readFileSync(SOURCE, 'utf8')) as OpenAPI3;
  const ast = await openapiTS(document, { silent: true });
  const header =
    COMMENT_HEADER +
    '// Types of the Shelfy Web API, from crates/server/openapi.json.\n' +
    `// Regenerate with \`${COMMAND}\`.\n\n`;
  const config = (await prettier.resolveConfig(OUTPUT)) ?? {};
  return prettier.format(header + astToString(ast), { ...config, filepath: OUTPUT });
}

const relative = path.relative(ROOT, OUTPUT);
const text = await render();
if (process.argv.includes('--check')) {
  const current = fs.existsSync(OUTPUT) ? fs.readFileSync(OUTPUT, 'utf8') : null;
  if (current === text) {
    console.log(`ok     ${relative}`);
  } else {
    console.error(`stale  ${relative}: run \`${COMMAND}\` and commit the result`);
    process.exit(1);
  }
} else {
  fs.mkdirSync(path.dirname(OUTPUT), { recursive: true });
  fs.writeFileSync(OUTPUT, text);
  console.log(`wrote  ${relative}`);
}
